import type { Metadata } from 'next'
import './globals.css'
import NavBar from '@/components/navbar'
import Footer from '@/components/footer'


export const metadata: Metadata = {
  title: 'Respo',
  description: 'Generated by noah408',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return(
    <html lang="pt">
      <body className="w-full min-h-full bg-[#212722] m-0 p-0 flex flex-col justify-between items-center">
          <NavBar/>
          <div className='w-full h-fit'>
            {children}
          </div>
          <Footer/>
      </body>
    </html>
  )
}
